from PIL import Image, ImageDraw, ImageFont
import os
from pathlib import Path

class WatermarkService:
    @staticmethod
    def add_watermark(image_path: str, output_path: str, text: str = "Generated by WeddingAI") -> str:
        """Add text watermark to image"""
        try:
            # Open image
            image = Image.open(image_path)
            
            # Create drawing context
            draw = ImageDraw.Draw(image)
            
            # Calculate text size and position
            width, height = image.size
            
            # Try to use a font, fallback to default if not available
            try:
                font_size = int(height * 0.05)  # 5% of image height
                font = ImageFont.truetype("/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf", font_size)
            except:
                font = ImageFont.load_default()
            
            # Get text bounding box
            bbox = draw.textbbox((0, 0), text, font=font)
            text_width = bbox[2] - bbox[0]
            text_height = bbox[3] - bbox[1]
            
            # Position at bottom right with padding
            padding = 20
            x = width - text_width - padding
            y = height - text_height - padding
            
            # Draw semi-transparent rectangle behind text
            rect_padding = 10
            draw.rectangle(
                [x - rect_padding, y - rect_padding, 
                 x + text_width + rect_padding, y + text_height + rect_padding],
                fill=(0, 0, 0, 128)
            )
            
            # Draw text
            draw.text((x, y), text, fill=(255, 255, 255, 230), font=font)
            
            # Save watermarked image
            image.save(output_path, quality=95)
            
            return output_path
            
        except Exception as e:
            raise Exception(f"Failed to add watermark: {str(e)}")
    
    @staticmethod
    def add_watermark_pattern(image_path: str, output_path: str) -> str:
        """Add diagonal watermark pattern across image"""
        try:
            image = Image.open(image_path)
            width, height = image.size
            
            # Create transparent overlay
            overlay = Image.new('RGBA', (width, height), (255, 255, 255, 0))
            draw = ImageDraw.Draw(overlay)
            
            # Try to use a font
            try:
                font = ImageFont.truetype("/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf", 30)
            except:
                font = ImageFont.load_default()
            
            text = "WATERMARK"
            
            # Draw diagonal pattern
            for i in range(-height, width, 200):
                for j in range(0, height, 150):
                    draw.text((i, j), text, fill=(255, 255, 255, 50), font=font)
            
            # Composite images
            if image.mode != 'RGBA':
                image = image.convert('RGBA')
            
            watermarked = Image.alpha_composite(image, overlay)
            
            # Convert back to RGB if needed
            if watermarked.mode == 'RGBA':
                watermarked = watermarked.convert('RGB')
            
            watermarked.save(output_path, quality=95)
            
            return output_path
            
        except Exception as e:
            raise Exception(f"Failed to add watermark pattern: {str(e)}")