from pydantic_settings import BaseSettings
from typing import List, Optional
import os

class Settings(BaseSettings):
    # ============================================
    # ENVIRONMENT
    # ============================================
    ENVIRONMENT: str = "development"  # development, staging, production
    DEBUG: bool = False
    
    # ============================================
    # DATABASE
    # ============================================
    DATABASE_URL: str
    DB_POOL_SIZE: int = 10
    DB_MAX_OVERFLOW: int = 20
    DB_POOL_TIMEOUT: int = 30
    DB_POOL_RECYCLE: int = 3600
    
    # ============================================
    # SECURITY
    # ============================================
    SECRET_KEY: str
    ALGORITHM: str = "HS256"
    ACCESS_TOKEN_EXPIRE_MINUTES: int = 30
    
    # Rate Limiting
    RATE_LIMIT_PER_MINUTE: int = 60
    RATE_LIMIT_PER_HOUR: int = 1000
    
    # ============================================
    # GOOGLE OAUTH
    # ============================================
    GOOGLE_CLIENT_ID: str
    GOOGLE_CLIENT_SECRET: str
    
    # ============================================
    # GEMINI API
    # ============================================
    GEMINI_API_KEY: str
    GEMINI_TIMEOUT: int = 120  # seconds
    GEMINI_MAX_RETRIES: int = 3
    
    # ============================================
    # PAYMENT (RAZORPAY)
    # ============================================
    PAYMENT_TEST_MODE: bool = False
    RAZORPAY_KEY_ID: str
    RAZORPAY_KEY_SECRET: str
    RAZORPAY_WEBHOOK_SECRET: Optional[str] = None
    
    # ============================================
    # FILE STORAGE - AWS S3 (PRODUCTION)
    # ============================================
    USE_S3: bool = True  # Set to True in production
    AWS_REGION: str = "ap-south-1"  # Mumbai region
    AWS_ACCESS_KEY_ID: Optional[str] = None
    AWS_SECRET_ACCESS_KEY: Optional[str] = None
    S3_BUCKET_NAME: Optional[str] = None
    S3_ENDPOINT_URL: Optional[str] = None  # For LocalStack testing
    
    # Local storage (fallback/development)
    TEMPLATE_PREVIEW_DIR: str = "template_previews"
    UPLOAD_DIR: str = "./uploads"
    GENERATED_DIR: str = "./generated"
    MAX_FILE_SIZE: int = 10485760  # 10MB
    
    # ============================================
    # URLS
    # ============================================
    FRONTEND_URL: str
    BACKEND_URL: str
    
    # ============================================
    # REDIS (FOR CACHING & TASK QUEUE)
    # ============================================
    REDIS_URL: str = "redis://localhost:6379/0"
    REDIS_MAX_CONNECTIONS: int = 50
    CACHE_TTL: int = 3600  # 1 hour
    
    # ============================================
    # CELERY (BACKGROUND TASKS)
    # ============================================
    CELERY_BROKER_URL: Optional[str] = None  # e.g., redis://localhost:6379/1
    CELERY_RESULT_BACKEND: Optional[str] = None
    
    # ============================================
    # WATERMARK
    # ============================================
    WATERMARK_TEXT: str = "Generated by WeddingAI"
    
    # ============================================
    # FREE TIER & SUBSCRIPTION
    # ============================================
    FREE_GENERATION_LIMIT: int = 2
    FREE_TEMPLATE_IDS: str = "1,2"
    BASIC_PLAN_PRICE: int = 20000
    BASIC_PLAN_CREDITS: int = 20
    
    # ============================================
    # MONITORING & LOGGING
    # ============================================
    LOG_LEVEL: str = "INFO"  # DEBUG, INFO, WARNING, ERROR
    SENTRY_DSN: Optional[str] = None  # For error tracking
    
    # ============================================
    # CORS
    # ============================================
    ALLOWED_ORIGINS: str = ""  # Comma-separated
    
    class Config:
        env_file = ".env"
        case_sensitive = True
    
    @property
    def free_template_ids_list(self) -> List[int]:
        return [int(id.strip()) for id in self.FREE_TEMPLATE_IDS.split(",")]
    
    @property
    def is_production(self) -> bool:
        return self.ENVIRONMENT == "production"
    
    @property
    def cors_origins(self) -> List[str]:
        """Parse CORS origins from comma-separated string"""
        if self.ALLOWED_ORIGINS:
            return [origin.strip() for origin in self.ALLOWED_ORIGINS.split(",")]
        return [self.FRONTEND_URL]
    
    @property
    def s3_config(self) -> dict:
        """Return S3 configuration"""
        return {
            "region_name": self.AWS_REGION,
            "aws_access_key_id": self.AWS_ACCESS_KEY_ID,
            "aws_secret_access_key": self.AWS_SECRET_ACCESS_KEY,
            "endpoint_url": self.S3_ENDPOINT_URL
        }

settings = Settings()